### ISSUE TITLE
Not able to import in postman

### ISSUE THREAD

**Issue by varun77sports** [forcedotcom/postman-salesforce-apis#27]
I am not able to import the folders or the individual JSON's in postman.

getting the below error. 

![image](https://user-images.githubusercontent.com/13214964/94348901-a8453b00-005d-11eb-9be1-fd80a136a3e6.png)

**Comment by scolladon** [comment]
Hi @varun77sports 

Have you tried to import the last [release](https://github.com/scolladon/postman-salesforce-apis/releases/tag/v0.2.1) ?

**Comment by pozil** [comment]
Hi @varun77sports, I suspect that you tried to import the repo content.
Make sure that you import the `salesforce-apis.postman_export.json` file available form the releases.

**Comment by pozil** [comment]
Closing after inactivity. Please reopen the issue or comment if the issue is still valid.
