### ISSUE TITLE
REST->SObject Create, endpoint URL is {{_endpoint}}/services/data/v{{version}}/sobjects/Attachment

### ISSUE THREAD

**Issue by BoonPlus** [forcedotcom/postman-salesforce-apis#36]
According to this blog..
 https://developer.salesforce.com/blogs/2020/03/explore-the-salesforce-apis-with-a-postman-collection.html

The original endpoint URL is...
{{_endpoint}}/services/data/v{{version}}/sobjects/<SOBJECT_NAME>

Not...
{{_endpoint}}/services/data/v{{version}}/sobjects/Attachment

**Comment by pozil** [comment]
Hi @BoonPlus, thanks for reporting this.
I've updated the request URL template to align with the other REST sObject CRUD operations:
```
{{_endpoint}}/services/data/v{{version}}/sobjects/<SOBJECT_API_NAME>
```
