### ISSUE TITLE
Metadata -> SOAP DescribeValueType -> Body -> <type>, found an extra "}" 

### ISSUE THREAD

**Issue by BoonPlus** [forcedotcom/postman-salesforce-apis#37]
The  last "}" should be removed.
<type>{http://soap.sforce.com/2006/04/metadata}<METADATA_TYPE_NAME>}</type>

The correct one should look like this...
<type>{http://soap.sforce.com/2006/04/metadata}<METADATA_TYPE_NAME></type>

**Comment by pozil** [comment]
Hi @BoonPlus, thanks for reporting this. I just fixed the issue.
