### ISSUE TITLE
Invalid session ID 

### ISSUE THREAD

**Issue by dariofinotti** [forcedotcom/postman-salesforce-apis#40]
Hi,
following the guide I was able to connect and use collection.
Closing and reopening the next day I received this message:
    {
        "message": "Session expired or invalid",
        "errorCode": "INVALID_SESSION_ID"
    }
I tried to login again using the button " Get new access token" but also using a new token nothing changes.
Anyone has the same issue?

Postman Version 8.0.5
win32 10.0.19041 / x64 

Uploaded settings image

thanks
![Immagine 2021-02-09 180151](https://user-images.githubusercontent.com/50618030/107399424-ff294980-6b00-11eb-9e96-aca608912c9a.png)

**Comment by pozil** [comment]
Hi @dariofinotti. Can you double check that you have correctly set the `_endpoint` collection variable with your instance url?
Don't forget to save after selecting the token and updating the variable.

**Comment by dariofinotti** [comment]
Hi @pozil,
I found the problem, it was the Add auth data to: Request URL, the correct one is request hearders.
Thanks

**Comment by pozil** [comment]
Glad you solved it. Thanks for using the collection.
