### ISSUE TITLE
Header Host contains invalid characters

### ISSUE THREAD

**Issue by thoffman-sfdc** [forcedotcom/postman-salesforce-apis#41]
Hi @pozil - I'm editing Katia Hage's custom channels badge and I'm getting the following error when I run through the steps: Error: Header "Host" contains invalid characters

Things worked fine yesterday but after testing today with two fresh pre-release orgs ran into the same issue both times. Any idea what could be going on?

**Comment by thoffman-sfdc** [comment]
Just following up on this @pozil - The issue was an artifact when copying the instance_url from the token details view. I'm guessing most devs will be able to troubleshoot this, but we might want to add a note to the instructions since we're pointing some Trailhead content to these instructions. Thanks!

**Comment by pozil** [comment]
Hi @thoffman-sfdc. Thanks for the extra info, I wish we could automate this part and get rid of the `instance_url` copy/pasting. My guess is that you also copied a line break.
I'm going to update the instructions to warn users.
