### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by jkenzer** [forcedotcom/postman-salesforce-apis#42]
I'm following the instructions from the README.md and when I get to authorization, I click on Get New Access Token and I get a web browser with the following text:

error=invalid_client_id&error_description=client%20identifier%20invalid

Do I need to go into Salesforce and get a clientId first or is this something that should happen with the initial auth request?

I'm using Postman Desktop.

**Comment by pozil** [comment]
Hi @jkenzer, the `clientId` variable is be pre-filed when you get the collection:

![Screen Shot 2021-02-15 at 09 49 18](https://user-images.githubusercontent.com/5071767/107924382-23f34600-6f73-11eb-8dce-9ae327a7089f.png)

Can you make sure that the value of the `url` variable matches the type of org you're trying to connect to.

**Comment by jkenzer** [comment]
@pozil Thanks. That was it. I deleted the collection and re-forked it and it's working. I must have accidently deleted the clientId on the first go around. Sorry for requesting tech support.
