### ISSUE TITLE
Profile cannot be found

### ISSUE THREAD

**Issue by willian-lynk** [forcedotcom/postman-salesforce-apis#44]
After click on "Salesforce developers" team, postman say that profile cannot be found.

![image](https://user-images.githubusercontent.com/78502820/111649421-1e438700-87e3-11eb-9b1f-6b08a527bdf8.png)

**Comment by apieri** [comment]
Sorry, where are the collections to import in postman?

**Comment by pozil** [comment]
Hi all, thanks for reporting this issue.

Unfortunately, I'm unable to reproduce the issue so I suspect that it was a temporary problem with the Postman infrastructure.
Just in case, could you make sure that you're running the [latest Postman app version](https://learning.postman.com/docs/getting-started/installation-and-updates/#updating-postman) (v8.0.7 at time of writing)?
Let me know if the problem persists.

**Comment by pozil** [comment]
> Sorry, where are the collections to import in postman?

The collection are hosted under the [Salesforce Developers team page](https://www.postman.com/salesforce-developers). See our documentation:
- [Install using the Postman desktop app](../install-with-app.md) (recommended)
- [Install using the Postman web UI](../install-with-web.md) (longer setup, requires CORS configuration in Salesforce org)

**Comment by willian-lynk** [comment]
> Hi all, thanks for reporting this issue.
> 
> Unfortunately, I'm unable to reproduce the issue so I suspect that it was a temporary problem with the Postman infrastructure.
> Just in case, could you make sure that you're running the [latest Postman app version](https://learning.postman.com/docs/getting-started/installation-and-updates/#updating-postman) (v8.0.7 at time of writing)?
> Let me know if the problem persists.

Same version here. The error persists

**Comment by pozil** [comment]
Could you try either of the following:
- Sign in the Postman app before trying to access the Salesforce Developers team
- Sign in the Postman web UI and try to fork the collection from [this url](https://www.postman.com/salesforce-developers).

Let me know if this works.

**Comment by willian-lynk** [comment]
* Sign in the Postman app before trying to access the Salesforce Developers team

This worked.
Thank you very much!

**Comment by pozil** [comment]
Glad this worked. Thanks for letting me know.
