### ISSUE TITLE
Authentication Fails on Flatpak desktop Postman

### ISSUE THREAD

**Issue by byteshiva** [forcedotcom/postman-salesforce-apis#49]
I'm unable to authenticate using desktop postman installed using flatpak on mx-linux (https://flathub.org/apps/details/com.getpostman.Postman)

It gets authenticated in the browser but it's not getting redirected to the desktop postman. Also, I've allowed opening popups

![image](https://user-images.githubusercontent.com/10637299/118235505-7a105080-b4b2-11eb-8751-909956683a70.png)

I see `xdg-open` is not redirecting to postman installed on linux. Am I missing something here?

![image](https://user-images.githubusercontent.com/10637299/118232301-f48aa180-b4ad-11eb-9331-abc6f8974d3d.png)

**Comment by pozil** [comment]
Hi @byteshiva, this looks like a flatpak client bug, not a bug with the collection. I suggest that you reach out to them directly for support.

If the authentication doesn't work with the desktop app, I suggest that you use the [Postman Web UI](https://github.com/forcedotcom/postman-salesforce-apis/blob/master/install-with-web.md).
