### ISSUE TITLE
salesforce-api.postman_export.json download

### ISSUE THREAD

**Issue by cg-madhu** [forcedotcom/postman-salesforce-apis#50]
How do I download salesforce-api.postman_export.json  file to import it into Postman

**Comment by pozil** [comment]
Hi @cg-madhu. We no longer rely on the JSON file to install the collection, we're now using Postman Public Workspaces (more convenient, allows updates).
Take a look at [the readme](https://github.com/forcedotcom/postman-salesforce-apis) to see how you can install the collection with the Postman desktop app or web UI.
