### ISSUE TITLE
In the Salesforce collection, Bulk v1 > Query folder is missing

### ISSUE THREAD

**Issue by jarmstrong-sfdc** [forcedotcom/postman-salesforce-apis#52]
Under the **Bulk v1** API, it appears that the **Query** folder and all respective calls are missing from the collection.

**Comment by pozil** [comment]
Thanks for reporting this and for your patience @jarmstrong-sfdc. We've added the Query folder for Bulk API v1.
Simply pull the collection to get the latest changes.
