### ISSUE TITLE
Not finding JSON file to import

### ISSUE THREAD

**Issue by kutuvan** [forcedotcom/postman-salesforce-apis#53]
Hello,

Where can I find the JSON file to import in Postman?

Thanks.

Regards,
MB

**Comment by gfarb** [comment]
@kutuvan postman-salesforce-apis no longer relies on the JSON file. You can install it from the Postman Public Workspace

- https://developer.salesforce.com/blogs/2021/01/explore-the-salesforce-apis-with-the-upgraded-postman-collection.html
- https://www.postman.com/salesforce-developers/workspace/salesforce-developers/overview

**Comment by kutuvan** [comment]
Thank you !!!

**Comment by kutuvan** [comment]
Can I import as local? I see them as Global.

**Comment by kutuvan** [comment]
I was able to do via Creating Fork. Thanks.
