### ISSUE TITLE
Access Tokens Timing Out 

### ISSUE THREAD

**Issue by drobertsADF** [forcedotcom/postman-salesforce-apis#55]
Getting some unusual behavior from the Login flow. When clicking the `Get New Access Token` box, it is timing out and never getting a new token. I've done a few troubleshooting steps: reset my security token in the sandbox, cleared cookies in both postman and chrome, inspected the consoles in both postman and chrome, but there isn't anything that seems to indicate the issue. Any ideas? 

## Error message from Postman: 

`Error: OAuth 2.0 request timed out. Please try again.`

**Comment by gfarb** [comment]
@drobertsADF what OS and Postman client version are you using? 

There is an open issue right now in [postman-app-support](https://github.com/postmanlabs/postman-app-support/issues/9542) that seems related. Have you updated Postman recently or tried via [postman.co](postman.co)? You could also try the [potential workaround](https://github.com/postmanlabs/postman-app-support/issues/9542#issuecomment-783333023).

**Comment by pozil** [comment]
I couldn't reproduce the issue with Postman latest desktop app (version 8.7.0).
Is there any additional info that you could share @drobertsADF?

**Comment by drobertsADF** [comment]
It appears that it was something with the browser and Postman. Closing both applications and restarting fresh worked. Thanks everyone !
