### ISSUE TITLE
Metadata -> SOAP List Metadata INVALID_SESSION_ID

### ISSUE THREAD

**Issue by ram4ufriends** [forcedotcom/postman-salesforce-apis#56]
I have configured Postman and am able to execute most of the calls. But for Metadata -> SOAM List Metadata I am getting the below error. Does anything specific need to be done for SOAP calls?

<faultcode>sf:INVALID_SESSION_ID</faultcode>
 <faultstring>INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session</faultstring>

**Comment by pozil** [comment]
Hi @ram4ufriends these are SOAP requests (as indicated in their name). This means that you need a SOAP session to use them. The default authentication for the collection is OAuth 2.0 and that's not compatible with SOAP.
If you want to call SOAP APIs, you need to authenticate with **Auth > SOAP Login**. This requires that you set these collection variables beforehand: `username`, `password` and `secretToken`.
