### ISSUE TITLE
The instructions inside install-with-app.md are not quite right for Postman on Windows

### ISSUE THREAD

**Issue by davidjbrossard** [forcedotcom/postman-salesforce-apis#58]
There is no top-level search bar in the Windows app AFAIK. You have to go the web to run that search and find the SF Developers team.

See install-with-app.md

**Comment by gfarb** [comment]
@davidjbrossard I just installed the Postman app (v9.0.8) on my PC running Windows 10 and the top search bar was there as seen in the screenshots attached to this comment
![Screenshot 2021-11-10 133230](https://user-images.githubusercontent.com/22826414/141172909-e96bcc0e-8537-4c93-8ea9-0a53c7df243e.png)
![Screenshot 2021-11-10 133254](https://user-images.githubusercontent.com/22826414/141172907-598cbcc3-a2b1-4fb3-906a-21dcb237301f.png)

**Comment by pozil** [comment]
Thanks for helping and providing screenshots @gfarb, much appreciated.
@davidjbrossard does that solve the issue?
