### ISSUE TITLE
How should {{url}}{{site}}/services/oauth2 be used in the Auth folder, what is each for?

### ISSUE THREAD

**Issue by colinkenworthy** [forcedotcom/postman-salesforce-apis#59]
Should only one OR the other be used?  I can't think what should go into {{site}} and no documents mention it.

**Comment by pozil** [comment]
Hi @colinkenworthy thanks for reaching out, I'll update the documentation.
The `url` variable is always required.
The `site` variable is used in combination with `url` when working with Experience Cloud sites with subdomains.

**Comment by colinkenworthy** [comment]
Thank you for the explanation.
