### ISSUE TITLE
Postman times out waiting for access token

### ISSUE THREAD

**Issue by pogilvieCB** [forcedotcom/postman-salesforce-apis#62]
I'm trying to authenticate the collection to my developer org.  I'm able to authenticate successfully to my developer org but postman never gets the access token.

I'm using postman Version 9.24.2 which looks a bit different from the demos I've been watching.

Here's a screen shot of the situation.  

<img width="2518" alt="postname-auth" src="https://user-images.githubusercontent.com/70237646/180647167-7b8902c6-f073-4779-b324-46bf7d141fc3.png">

**Comment by pozil** [comment]
Hi @pogilvieCB, this is likely caused by a security restriction on Chrome.
Try clicking on this icon to allow the callback to Postman:

![Screen Shot 2022-07-25 at 10 41 31](https://user-images.githubusercontent.com/5071767/180735841-4ead305e-4471-4cd8-a968-8b5755778701.png)

**Comment by mehmetbybz** [comment]
https://app.getpostman.com/join-team?invite_code=8e9b865309f6e167f2c1a437e4a731dd

**Comment by mehmetbybz** [comment]
https://app.getpostman.com/join-team?invite_code=8e9b865309f6e167f2c1a437e4a731dd
