### ISSUE TITLE
Problem with "Authenticate with Salesforce"

### ISSUE THREAD

**Issue by eferalgan234** [forcedotcom/postman-salesforce-apis#63]
Could someone advise me on following problem.
Following instructions(https://github.com/forcedotcom/postman-salesforce-apis/blob/master/install-with-app.md#authenticate-with-salesforce) at Authenticate-with-salesforce 
Chrome opens page with message
"Your call is authenticated
A new window should open directing you back to the Postman app. If nothing happens, check to make sure your browser allows pop-ups." 
Then opens new window
KIO Client throws error "Could not find any application or handler for postman://app/oauth2..."
Focus don't go to Postman application.
I have defined File associations for Postman in sections Applications, x-content and x-epoc. 

With Chromium browser focus goes to Postman application, but reaction.

OS: Kubuntu 20
KDE 5
Browser: Chrome
Postman installed with snap.

**Comment by pozil** [comment]
Hi @eferalgan234, you'll want to ask this question in Postman support forums as this issue is not specific to the Salesforce collection.
As an alternative to using the Postman desktop app you can also use the [Postman Web UI](https://github.com/forcedotcom/postman-salesforce-apis/blob/master/install-with-web.md). It has the same features.

**Comment by eferalgan234** [comment]
Thanks for coming back to me.
I was wondering if there are other ways (and there are !) of getting that auth URL parsed (split by arguments) and saved directly into Postman. I'm novice to Postman, so couldn't find right variables to fill in.
By the way, you have a nice post https://developer.salesforce.com/blogs/2022/08/writing-apex-rest-services-and-when-not-to, I so inspired by that !
