### ISSUE TITLE
Download the collection without using Postman

### ISSUE THREAD

**Issue by KnokkeLeZoute** [forcedotcom/postman-salesforce-apis#72]
Hi all!
Our team doesn't use Postman to call Salesforce APIs because we prefer tools like ReadyAPI or Bruno.
This repository only seems to contain documentation about how to import the collection from Postman.
Is there a way to download the collection without using Postman?
Regards,
Rémy.

**Comment by pozil** [comment]
Hi @KnokkeLeZoute. I'm afraid that unless your tools can import the Postman format you won't be able to use the collection.
