### ISSUE TITLE
Unable to remove Initial Value on general Salesforce Platform API Authorization Variable

### ISSUE THREAD

**Issue by fabrizioorsinigit** [forcedotcom/postman-salesforce-apis#73]
Good morning, 
inside Salesforce Developer workspace, on the Salesforce Platform APIs collection a clientId appears in the "initial value" and in the "current value": maybe it would be necessary to remove it. Trying to remove it and save the information appears again. Is that a problem? If yes, Would it be possible to remove it permanently?
Thank you in advance.

**Comment by pozil** [comment]
Hi @fabrizioorsinigit thanks for reaching out. The initial `clientId` field is shared on purpose and is not sensitive provided that we don't share the client secret value.

Sharing the client ID allow us to provide you with an implicit OAuth grant that doesn't require that you create a connected app (you are using our shared connected app).

**Comment by fabrizioorsinigit** [comment]
Hi @pozil , thank you so much for you explanation!
Best regards.
